// REG_OP(Add)
//     .INPUT(x1, TensorType({DT_FLOAT}))
//     .INPUT(x2, TensorType({DT_FLOAT}))
//     .OUTPUT(y, TensorType({DT_FLOAT}))
//     .OP_END_FACTORY_REG(Add)
// REG_OP(FurthestPointSamplingWithDist)
//     .INPUT(points_dist, TensorType({DT_FLOAT}))
//     .INPUT(nearest_temp, TensorType({DT_FLOAT}))
//     .OUTPUT(index, TensorType({DT_INT32}))
//     .REQUIRED_ATTR(num_points, Int)
//     .OP_END_FACTORY_REG(FurthestPointSamplingWithDist)
